site_name: PocketID
theme:
  name: material
  palette:
    primary: 'cyan'
    accent: 'indigo'
  logo: 'assets/logo.png'
  feature:
    tabs: false
pages:
  - Home: index.md
  - Android:
    - Latest: android/index.md
    - v0.1.3: android/v0.1.3.md
    - v0.1.1: android/v0.1.1.md
  - iOS:
    - Latest: ios/index.md
  - Web:
    - Latest: web/index.md
repo_name: 'Serind/PocketID'
repo_url: 'https://github.com/Serind/PocketID'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
