site_name: PocketID
theme:
  name: bootstrap
pages:
  - Home: index.md
  - Android:
    - Latest: android/index.md
    - v0.1.3: android/v0.1.3.md
    - v0.1.1: android/v0.1.1.md
  - iOS:
    - Latest: ios/index.md
  - Web:
    - Latest: web/index.md
